### ISSUE TITLE
Hello, I have also written a MCTS, but it can only simulate 10W times, and then the memory leak will occur. Is there any way to solve it?  

### ISSUE THREAD

**Issue by 177715031** [030helios/OthelloMCTS-DataOriented#1]

**Comment by 030helios** [comment]
may I see your code?

**Comment by 177715031** [comment]
could you send me e-mail address?I can send to you.Thank you.

**Comment by 030helios** [comment]
a95037@gmail.com

**Comment by 177715031** [comment]
already send.Thank you.

**Comment by 030helios** [comment]
see if this helps:
    qDebug()<< "MCTS_Nodes"<< node_count<<"剩余落子点数:"<<best_child->maxChildrenNum;
    delete node; //here

**Comment by 177715031** [comment]
It does not work.the same problem.

**Comment by 030helios** [comment]
then maybe give it a destructor
Node::~Node()
{
    for(auto child :children)
        delete child;
}

**Comment by 177715031** [comment]
![image](https://user-images.githubusercontent.com/70942569/124425872-c897e800-dd9b-11eb-9c45-54924f0d475c.png)
It can not add the fuction

**Comment by 030helios** [comment]
then we work around it
    
    void Node::delNode()
    {
        for (auto child : children)
            child->delNode();
        delete this;
    }

    qDebug() << "MCTS_Nodes" << node_count << "剩余落子点数:" << best_child->maxChildrenNum;
    node->delNode();

**Comment by 177715031** [comment]
It already does not work.

**Comment by 030helios** [comment]
well if you can't delete it don't allocate the node yourself.

**Comment by 177715031** [comment]
I tried to delete the nodes, but it didn't work, and Monte Carlo searches would not work if no nodes were allocated.

**Comment by 177715031** [comment]
I try again ,find it will be crashed whatever times I set simulation.

**Comment by 030helios** [comment]
No. what I meant is don't allocate them **yourself**

Store the children in, say, a vector. Avoid using thing like "node newnode = new node".
something like

    node newchild
    //do your expand here
    children.push_back(newchild)

**Comment by 030helios** [comment]
this way the default constructor will deallocate the children for you.

**Comment by 177715031** [comment]
I have a try
